### ISSUE TITLE
Minimal needed RBAC permissions

### ISSUE THREAD

**Issue by pastx** [utkuozdemir/pv-migrate#205] opened 2022-11-18 15:40 UTC
First of all, thank you for this great tool!

I'm trying to deploy pv-migrate in a container in a restricted Kubernetes cluster. I'm trying to create minimal RBAC roles needed for a successful migration on the same cluster between two namespaces.

Is there any list or is there a way (better than going from one error to another) to understand what apiGroups, resources, and verbs are needed for each namespace?

Thank you.

**Comment by utkuozdemir** [comment] 2022-11-19 13:26
Hi, thank you for reporting. This is actually a duplicate of https://github.com/utkuozdemir/pv-migrate/issues/152#issue-1132765898 - I'll close this one and track it there.

But it is an indicator is that it is a problem many people are facing. I'll try to have a look into it.

In the meantime, you can have a look to the Helm chart: https://github.com/utkuozdemir/pv-migrate/tree/master/helm/pv-migrate/templates

These are the resources that might get created by pv-migrate - it also depends on the strategy and passed flags. Iy can give you an idea on what roles you might be missing.

**Closed by utkuozdemir** 2022-11-19 13:26 UTC
