### ISSUE TITLE
"failed to install on source: failed to install helm chart: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline"

### ISSUE THREAD

**Issue by ahamroun10** [utkuozdemir/pv-migrate#301] opened 2024-05-17 13:39 UTC
i have this code error when running pv-migrate
also i did increase helm timeout

**Comment by utkuozdemir** [comment] 2024-05-17 14:03
It's impossible for me to help you with this little information. Please follow the bug report template and provide additional context.

**Comment by utkuozdemir** [comment] 2024-05-17 14:05
Also, do your cluster assign an IP to LoadBalancer type services? If it gets stuck at pending, it can be the cause for the helm wait to fail.

If the service needs a specific annotations etc. to be get an IP, you can pass them using `--helm-*` flags.

**Comment by ahamroun10** [comment] 2024-05-17 14:18
May 17 15:18:03.190 DBG Service does not have load balancer ingress IP address: pr-keyrus-data/pv-migrate-eaadd-src-sshd source=pr-keyrus-data/data-pr-clickhouse-data-keyrus-data-shard0-0 dest=pr-keyrus-data/data-pr-clickhouse-data-keyrus-new-data-shard0-0-backup attempt_id=eaadd strategy=lbsvc i have this error when passing debug mode

**Comment by mastpsp** [comment] 2024-09-11 04:33
@ahamroun10 Hello. You can try --strategies local , it worked for me

**Comment by utkuozdemir** [comment] 2024-12-17 00:31
It seems the lbsvc service could not get an IP address. This is related to the cluster configuration, and this tool cannot do anything other than failing the way it does in this case. Closing.

**Closed by utkuozdemir** 2024-12-17 00:31 UTC
