### ISSUE TITLE
All strategies are failing

### ISSUE THREAD

**Issue by danieldaeschle** [utkuozdemir/pv-migrate#133] opened 2021-12-03 07:46 UTC
**Describe the bug**
All strategies are failing

**Expected behavior**
At least one should work.

**Console output**
```
🚀  Starting migration
💡  PVC wordembedding-resources-pvc is mounted to node aks-heavyram-33180665-vmss000000, ignoring...
💭  Will attempt 3 strategies: mnt2, svc, lbsvc
🚁  Attempting strategy: mnt2
🦊  Strategy 'mnt2' cannot handle this migration, will try the next one
🚁  Attempting strategy: svc
🔑  Generating SSH key pair
creating 7 resource(s)
beginning wait for 7 resources with timeout of 1m0s
Deployment is not ready: default/pv-migrate-ff8y3-sshd. 0 out of 1 expected pods are ready
📂  Copying data...   0% |                                                                                 | () [0s:0s]�   Cleaning up
uninstall: Deleting pv-migrate-ff8y3
Starting delete for "pv-migrate-ff8y3-sshd" Service
Starting delete for "pv-migrate-ff8y3-rsync" Job
Starting delete for "pv-migrate-ff8y3-sshd" Deployment
Starting delete for "pv-migrate-ff8y3-sshd" Secret
Starting delete for "pv-migrate-ff8y3-rsync" Secret
Starting delete for "pv-migrate-ff8y3-sshd" ServiceAccount
Starting delete for "pv-migrate-ff8y3-rsync" ServiceAccount
beginning wait for 7 resources to be deleted with timeout of 1m0s
purge requested for pv-migrate-ff8y3
✨  Cleanup done
🔶  Migration failed with this strategy, will try with the remaining strategies
🚁  Attempting strategy: lbsvc
🔑  Generating SSH key pair
creating 4 resource(s)
beginning wait for 4 resources with timeout of 1m0s
Service does not have load balancer ingress IP address: default/pv-migrate-1ei5r-sshd
Service does not have load balancer ingress IP address: default/pv-migrate-1ei5r-sshd
Service does not have load balancer ingress IP address: default/pv-migrate-1ei5r-sshd
Service does not have load balancer ingress IP address: default/pv-migrate-1ei5r-sshd
Service does not have load balancer ingress IP address: default/pv-migrate-1ei5r-sshd
Service does not have load balancer ingress IP address: default/pv-migrate-1ei5r-sshd
Service does not have load balancer ingress IP address: default/pv-migrate-1ei5r-sshd
Service does not have load balancer ingress IP address: default/pv-migrate-1ei5r-sshd
Service does not have load balancer ingress IP address: default/pv-migrate-1ei5r-sshd
🧹  Cleaning up
uninstall: Deleting pv-migrate-1ei5r
Starting delete for "pv-migrate-1ei5r-sshd" Service
Starting delete for "pv-migrate-1ei5r-sshd" Deployment
Starting delete for "pv-migrate-1ei5r-sshd" Secret
Starting delete for "pv-migrate-1ei5r-sshd" ServiceAccount
beginning wait for 4 resources to be deleted with timeout of 1m0s
purge requested for pv-migrate-1ei5r
✨  Cleanup done
🔶  Migration failed with this strategy, will try with the remaining strategies
❌  Error: all strategies have failed
```

**Version**
 - AKS  1.20
 - Source and destination container runtimes [e.g. `containerd://1.4.4-k3s2`, `docker://19.3.6`]
 - pv-migrate version 0.7.2 (commit: 766fddb8040178e20d64490c32df141f818f61c6)
 - Installation method binary download
 - ReadWriteOnce (if I shut down the service that mounts it, it still does not work)

**Comment by danieldaeschle** [comment] 2021-12-03 07:50
Looks like the error is "Volume is already exclusively attached to one node and can't be attached to another"

**Comment by utkuozdemir** [comment] 2021-12-03 08:10
Thanks for reporting. Do you get the multi-attach error when you shut down both mounting pods on source and dest (so that you don't need to pass --ignore-mounted)?

Please also enable debug json logging and share the logs here.

**Comment by danieldaeschle** [comment] 2021-12-03 08:16
I just found out that Azure keeps the pv mounted on one node. It looks like the service started on another node and couldn't mount it,

**Comment by utkuozdemir** [comment] 2021-12-03 08:21
Good finding, thanks. Can you share a sample of your PVC manifest, so I can see if there is an affinity/node selector or something on it? If there is, I can adapt the logic to schedule pv-migrate pods on the same node. 

Actually it already does something like that when --ignore-mounted is used but it seems it didn't work in your case for some reason.

**Comment by danieldaeschle** [comment] 2021-12-03 08:22
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xyz
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 8Gi
```

And I just tried to rename it.

**Comment by utkuozdemir** [comment] 2021-12-03 08:25
Cool, I didn't test it on azurefile volumes and volumes with multiple accessModes. I can give it a try in a few days and see if I can reproduce it.

**Comment by danieldaeschle** [comment] 2021-12-03 08:28
One access mode has the same problem, so this shouldn't matter.

**Comment by utkuozdemir** [comment] 2021-12-03 08:29
Weird, ReadWriteMany by definition can be mounted to multiple nodes at the same time.

**Comment by danieldaeschle** [comment] 2021-12-03 08:45
Oh.. okay..

**Comment by utkuozdemir** [comment] 2021-12-03 09:12
The official docs https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

But I just noticed that your pvc is ReadOnlyMany, not ReadWriteMany. So, one node can write at a time, but multiple can mount it as read-only.

This means the problem is probably on the destination side, as source is mounted as read-only by default.

**Comment by danieldaeschle** [comment] 2021-12-03 09:51
I think the problem occured with only `ReadWriteOnce` then. I changed my defintion after that. Could work if there is ReadyOnlyMany.

**Comment by danieldaeschle** [comment] 2021-12-03 09:52
I'm wondering why it can't be mounted on another node if the resources that needed it is deleted.

**Comment by utkuozdemir** [comment] 2021-12-06 16:20
Apologies for the question but are you the same person @danieldaeschle @upstream-dmahlberg ?

@upstream-dmahlberg was there something pv-migrate is doing wrong (bug etc.) or was it only misconfiguration on your side? Do I need to look into something?

**Comment by danieldaeschle** [comment] 2021-12-06 16:54
No, I'm not the same

**Comment by utkuozdemir** [comment] 2021-12-06 16:56
Sorry, got a bit confused 😄

**Comment by utkuozdemir** [comment] 2021-12-07 00:32
@danieldaeschle did you make any progress or do you have any new findings? I would need the debug logs in the JSON format to be able to help.

**Comment by danieldaeschle** [comment] 2021-12-07 14:19
I didn't really fixed it. Sometimes it worked sometimes now. If the filesize was to big it stopped too.. strange.

**Comment by utkuozdemir** [comment] 2021-12-07 22:36
I think your issue might be fixed by commit https://github.com/utkuozdemir/pv-migrate/commit/a3e60064fd99b4fd9bd2a92914363ccae18c7516 in v0.7.5.

Please give it a try and report if the issue persists.

**Comment by utkuozdemir** [comment] 2021-12-10 21:39
I fixed many issues during the last week or so. If you still face issues on >=v0.8.0, feel free to open a new ticket with debug json logs.

**Closed by utkuozdemir** 2021-12-10 21:39 UTC
